#+STARTUP: showall
#+TAGS: DOCS(d) CODING(c) TESTING(t) PLANING(p)
#+STARTUP: hidestars


* Open Source HeNB platform
** Overview							       :DOCS:

   [[http://femtoforum.org/femto/technical.php][Femto Forum]]

   The Femto Application Platform Interface (FAPI) is an initiative
   within the femto industry to encourage competition and innovation
   between suppliers of platform hardware, platform software and
   application software by providing a common API around which suppliers
   of each component can compete. In doing this, we imitate a long and
   distinguished engineering tradition of providing an
   “interchangeability of parts” to ensure that the systems vendors can
   take advantage of the latest innovations in silicon and software with
   the minimum of entry barrier, and the least amount of custom
   re-engineering.

* Interfaces
  Several APIs are defined, as follows:
  P1 – the Security coprocessor interface
  P2 – the Service Discovery Interface
  P3 – the GPS interface
  P4 – the Network Listen Results interface
  P5 – the PHY mode control interface
  P6 – the ciphering coprocessor interface
  P7 – the main datapath interface
  M1 – the scheduler interface

** LTE MAC Scheduler Interface Specification v1.11		       :DOCS:
   October 2010

   Index number: FF_Tech_001_v1.11

   This document specifies the MAC Scheduler interface. The goal of this
   interface specification is to allow the use of a wide range of
   schedulers which can be plugged into the eNodeB and to allow for
   standardized interference coordination interface to the scheduler.
*** DONE Interface definition for CSCHED SAP and SCHED SAP with Properties <2012-01-12 Thu> :CODING:
** LTE eNB L1 API Definition v1.11
   October 2010

   Index number: FF_Tech_002_v1.11

   This document describes an Application Programming Interface (API)
   which defines the interface between LTE L2/L3 software and L1
   PHY. Specifically, this L1 API defines both P5 and P7 of the Femto
   Forum LTE FAPI.

** LTE Network Monitor Mode Specification v1.01

   October 2010

   Index number: FF_Tech_003_v1.01

   This document specifies the Network Monitor Mode (NMM) module for
   LTE. Support for 3G and 2G is not in the scope of this document. The
   goal of this interface specification is to allow a femtocell to
   support cell RF self configuration and interference management
   according to requirements which, amongst others, include: carrier and
   cell id selection; DL TX power setting; UE TX power setting and
   frequency reference.

